### ISSUE TITLE
CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by KyriaAnnwyn** [gladzhang/ART#4]
Pytorch 1.12 + cuda 11.6
basicsr 1.4.2

Get this error:
`
2022-10-25 17:25:58,284 INFO: Loading ART model from experiments/pretrained_models/SR_ART_x2.pth, with param key: [params].
2022-10-25 17:25:58,402 INFO: Model [ARTModel] is created.
2022-10-25 17:25:58,402 INFO: Testing example...
Traceback (most recent call last):
  File "basicsr/test.py", line 51, in <module>
    test_pipeline(root_path)
  File "basicsr/test.py", line 46, in test_pipeline
    model.validation(test_loader, current_iter=opt['name'], tb_logger=None, save_img=opt['val']['save_img'])
  File "~/SuperResolution/ART/artenv/lib/python3.8/site-packages/basicsr/models/base_model.py", line 48, in validation
    self.nondist_validation(dataloader, current_iter, tb_logger, save_img)
  File "~/SuperResolution/ART/artenv/lib/python3.8/site-packages/basicsr/models/sr_model.py", line 157, in nondist_validation
    self.test()
  File "~/SuperResolution/ART/basicsr/models/art_model.py", line 23, in test
    img = F.pad(self.lq, (0, mod_pad_w, 0, mod_pad_h), 'reflect')
RuntimeError: CUDA error: no kernel image is available for execution on the device

`

**Comment by gladzhang** [comment]
Please check if there exists a file in the testing folder `datasets\example`. If you still meet this error, check the corresponding yml file in the folder `options\apply`. In yml file, the `dataroot_lq` should be the same with the provided testing example files folder. Thanks.
